name: travelapp
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  shared_preferences: ^2.0.15
  flutter_bloc: ^8.1.1
  flutter_screenutil: ^5.6.1
  flutter_rating_bar: ^4.0.1
  flutter_svg: ^1.1.6
  get: ^4.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/images/
  
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
    - family: Urbanist
      fonts:
        - asset: assets/fonts/Urbanist-Regular.ttf
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.otf
